<script src="<?= base_url() ?>/assets/js/jquery-3.2.1.min.js"></script>
<script src="<?= base_url() ?>/assets/js/popper.min.js"></script>
<script src="<?= base_url() ?>/assets/js/bootstrap.min.js"></script>
<script src="<?= base_url() ?>/assets/js/jquery.sticky.js"></script>
<script src="<?= base_url() ?>/assets/js/owl.carousel.min.js"></script>
<script src="<?= base_url() ?>/assets/js/jquery.shuffle.min.js"></script>
<script src="<?= base_url() ?>/assets/js/jquery.counterup.min.js"></script>
<script src="<?= base_url() ?>/assets/js/wow.min.js"></script>
<script src="<?= base_url() ?>/assets/js/jquery.meanmenu.min.js"></script>
<script src="<?= base_url() ?>/assets/js/jquery.magnific-popup.min.js"></script>
<script src="<?= base_url() ?>/assets/js/custom.js"></script>